create extension if not exists pgcrypto with schema extensions;

create table if not exists public.school_dialogue (
  id bigint generated by default as identity primary key,
  nickname varchar(10) not null check (char_length(trim(nickname)) between 1 and 10),
  message varchar(500) not null check (char_length(trim(message)) between 1 and 500),
  pin_hash text not null,
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists school_dialogue_public_latest_idx
  on public.school_dialogue (created_at desc)
  where is_hidden = false;

alter table public.school_dialogue enable row level security;

drop policy if exists "public can read visible school dialogue" on public.school_dialogue;
create policy "public can read visible school dialogue"
on public.school_dialogue
for select
to anon, authenticated
using (is_hidden = false);

revoke all on table public.school_dialogue from public, anon, authenticated;
grant select (id, nickname, message, created_at, updated_at)
  on public.school_dialogue to anon, authenticated;
grant all on table public.school_dialogue to service_role;

create or replace function public.create_school_dialogue(
  p_nickname text,
  p_message text,
  p_pin text
) returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_id bigint;
begin
  if char_length(trim(p_nickname)) not between 1 and 10
     or char_length(trim(p_message)) not between 1 and 500
     or p_pin !~ '^[0-9]{4}$' then
    raise exception 'invalid input';
  end if;

  insert into public.school_dialogue (nickname, message, pin_hash)
  values (trim(p_nickname), trim(p_message), extensions.crypt(p_pin, extensions.gen_salt('bf', 8)))
  returning id into new_id;
  return new_id;
end;
$$;

create or replace function public.update_school_dialogue(
  p_id bigint,
  p_nickname text,
  p_message text,
  p_pin text
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if char_length(trim(p_nickname)) not between 1 and 10
     or char_length(trim(p_message)) not between 1 and 500
     or p_pin !~ '^[0-9]{4}$' then
    raise exception 'invalid input';
  end if;

  update public.school_dialogue
  set nickname = trim(p_nickname), message = trim(p_message), updated_at = now()
  where id = p_id
    and is_hidden = false
    and pin_hash = extensions.crypt(p_pin, pin_hash);

  if not found then raise exception 'not allowed'; end if;
  return true;
end;
$$;

create or replace function public.delete_school_dialogue(
  p_id bigint,
  p_pin text
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_pin !~ '^[0-9]{4}$' then raise exception 'invalid input'; end if;

  delete from public.school_dialogue
  where id = p_id
    and is_hidden = false
    and pin_hash = extensions.crypt(p_pin, pin_hash);

  if not found then raise exception 'not allowed'; end if;
  return true;
end;
$$;

revoke execute on function public.create_school_dialogue(text, text, text) from public;
revoke execute on function public.update_school_dialogue(bigint, text, text, text) from public;
revoke execute on function public.delete_school_dialogue(bigint, text) from public;
grant execute on function public.create_school_dialogue(text, text, text) to anon, authenticated, service_role;
grant execute on function public.update_school_dialogue(bigint, text, text, text) to anon, authenticated, service_role;
grant execute on function public.delete_school_dialogue(bigint, text) to anon, authenticated, service_role;
